version: "2.4"
services:
  klee:
    container_name: klee-workenv
    image: "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
    tty: true
    volumes:
      - type: bind
        source: "${HOST_VOLUME_PATH}"
        target: /klee
      - type: bind
        source: "${SHARED_VOLUME_PATH}"
        target: /shared
      - type: bind
        source: "${HOST_DG_VOLUME_PATH}"
        target: /dg
  dg:
    container_name: klee-dg
    image: "mchalupa/dg:latest"
    tty: true
    volumes:
      - type: bind
        source: "${SHARED_VOLUME_PATH}"
        target: /shared
